---
tasks:
- name: Get vector rpm distrib
  ansible.builtin.get_url:
    url: "{{ vector_rpm_url }}"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    mode: "664"

- name: Install vector rpm packages
  become: true
  ansible.builtin.yum:
    name: "./vector-{{ vector_version }}-1.x86_64.rpm"
  notify: Start vector service

- name: Deploy Vector Config
  become: true
  ansible.builtin.template:
    src: "{{ vector_conf_template }}"
    dest: "{{ vector_conf_dest }}"
    mode: "664"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers