---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-1
    image: docker.io/pycontribs/centos:8
  - name: instance-2
    image: docker.io/pycontribs/ubuntu:latest
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    #image: quay.io/centos/centos:stream8
