---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
#  - name: Get information about vector
#    ansible.builtin.command: systemctl status vector
#    register: srv_res
#    changed_when: false
#  - name: Assert vector service
#    ansible.builtin.assert:
#      that:
#        - srv_res.rc == 0
#        - "'ActiveState=active' in srv_res.stdout_lines"
#        - "'LoadState=loaded' in srv_res.stdout_lines"
#        - "'SubState=running' in srv_res.stdout_lines"
  - name: Validate vector configuration
    ansible.builtin.command: vector validate
    register: vld_res
    changed_when: false

  - name: Check vector process PID
    shell: >
      echo -n $(pgrep vector)
    register: vector_pid

  - name: Assert vector configuragtion
    ansible.builtin.assert:
      that:
        - vld_res.rc == 0
        - "'Validated' == {{ vld_res.stdout_lines | map('trim') | list }}[-1]"

  - name: Check vector service
    assert:
      that: vector_pid.stdout != 0
      success_msg: "Service is running"
      fail_msg: "Service not running"
